# Generated by Django 4.1.2 on 2022-10-07 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_alter_album_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
