# Generated by Django 4.1.2 on 2022-11-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='song_images'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
